
language: node_js
node_js:
  - "8.0.0"
  
services:
  - postgresql

addons:
    postgresql: '9.6'


env:
  - DATABASE_URL='postgresql://postgres@localhost:5432/my_reg_numbers';


before_script:
  
  - psql -c 'create database my_reg_numbers;' -U postgres
  - psql -U postgres -d my_reg_numbers -a -f database.sql